"use client";

import Link from "next/link";
import { useState, type CSSProperties } from "react";
import { ProductGlyph } from "./ProductBrand";
import { templatePacks, type TemplateEvidence, type TemplateId, type TemplatePack } from "@/lib/product/templates";
import styles from "./product.module.css";

type DemoSurface = "overview" | "inbox" | "ask" | "agents" | "replay" | "outcome";

const demoNav: Array<{ id: DemoSurface; label: string; icon: string }> = [
  { id: "overview", label: "Overview", icon: "⌁" },
  { id: "inbox", label: "Change Inbox", icon: "⇄" },
  { id: "ask", label: "Ask Commonstate", icon: "?" },
  { id: "agents", label: "Agent Console", icon: "◇" },
  { id: "replay", label: "Replay", icon: "↺" },
  { id: "outcome", label: "Outcome", icon: "◎" },
];

function DemoPill({ status }: { status: string }) {
  return <span className={`${styles.productPill} ${styles[`productPill_${status === "eligible" ? "good" : status === "blocked" ? "bad" : "warn"}`]}`}>{status}</span>;
}

export function TemplateDemo({ templateId }: { templateId: Exclude<TemplateId, "blank"> }) {
  const pack = templatePacks[templateId];
  const [surface, setSurface] = useState<DemoSurface>("overview");
  const [question, setQuestion] = useState(pack.guidedQuestion);
  const [answerVisible, setAnswerVisible] = useState(false);
  const [selectedChange, setSelectedChange] = useState(pack.changes[0]);
  const [approved, setApproved] = useState<string[]>([]);
  const [rejected, setRejected] = useState<string[]>([]);
  const [runVisible, setRunVisible] = useState(false);
  const [replayVisible, setReplayVisible] = useState(false);
  const [outcomeRecorded, setOutcomeRecorded] = useState(false);
  const [selectedEvidence, setSelectedEvidence] = useState<TemplateEvidence | null>(null);
  const [manifestVisible, setManifestVisible] = useState(false);
  const style = {
    "--workspace-accent": pack.accent,
    "--workspace-accent-soft": pack.accentSoft,
    "--workspace-accent-foreground": pack.id === "agency-operations" ? "#0A0A0A" : "#FFFFFF",
  } as CSSProperties;

  return (
    <main className={styles.publicDemo} style={style}>
      <a className={styles.skipLink} href="#public-demo-main">Skip to demo</a>
      <aside className={styles.publicDemoRail}>
        <Link href="/" className={styles.consoleBrand}><ProductGlyph inverse /><span><strong>commonstate</strong><small>{pack.shortName} demo</small></span></Link>
        <div className={styles.recordedNotice}><i />Recorded deterministic<span>Public template fixture</span></div>
        <nav aria-label="Demo navigation">{demoNav.map((item) => <button key={item.id} className={surface === item.id ? styles.publicDemoNavActive : styles.publicDemoNav} onClick={() => setSurface(item.id)}><span>{item.icon}</span><strong>{item.label}</strong>{item.id === "inbox" ? <i>{pack.changes.length - approved.length}</i> : null}</button>)}</nav>
        <div className={styles.publicDemoRailFooter}><p>Not a production workspace</p><span>No private company data · no live actions</span></div>
      </aside>
      <div className={styles.publicDemoWorkspace}>
        <header className={styles.publicDemoTopbar}>
          <div><span style={{ background: pack.accent }}>{pack.shortName.slice(0, 2).toUpperCase()}</span><p><strong>{pack.name} template</strong><small>{pack.scopeKinds.join(" → ")}</small></p></div>
          <div><button className={styles.secondaryAction} onClick={() => { setAnswerVisible(false); setApproved([]); setRejected([]); setRunVisible(false); setReplayVisible(false); setOutcomeRecorded(false); setSurface("overview"); }}>Reset fixture</button><Link href={`/setup?template=${templateId}`} className={styles.primaryAction}>Tailor this pack →</Link><Link href="/login" className={styles.secondaryAction}>Sign in</Link></div>
        </header>
        <section id="public-demo-main" className={styles.publicDemoMain} tabIndex={-1}>
          <header className={styles.productViewHeading}><div><p className={styles.monoEyebrow}>{pack.eyebrow}</p><h1>{demoNav.find((item) => item.id === surface)?.label}</h1><p>{surface === "overview" ? pack.description : surface === "inbox" ? "Review synthetic source events before they become shared operational truth." : surface === "ask" ? "Try the pack’s core decision workflow with claim-level synthetic evidence." : surface === "agents" ? "See how configured agents receive scoped context, policy, and write budgets." : surface === "replay" ? "Compare the fixture’s original context with its newly approved state." : "Connect the recorded decision to a measurable learning without mutating a real system."}</p></div><span className={styles.demoFixtureBadge}>Fixture schema v1 · 24/24 evals</span></header>

          {surface === "overview" ? <DemoOverview pack={pack} onStart={() => setSurface("ask")} /> : null}
          {surface === "inbox" ? <DemoInbox pack={pack} selected={selectedChange} setSelected={setSelectedChange} approved={approved} rejected={rejected} approve={() => { setApproved((current) => [...new Set([...current, selectedChange.id])]); setRejected((current) => current.filter((id) => id !== selectedChange.id)); }} reject={() => { setRejected((current) => [...new Set([...current, selectedChange.id])]); setApproved((current) => current.filter((id) => id !== selectedChange.id)); }} /> : null}
          {surface === "ask" ? <DemoAsk pack={pack} question={question} setQuestion={setQuestion} answerVisible={answerVisible} ask={() => setAnswerVisible(true)} onEvidence={(id) => setSelectedEvidence(pack.evidence.find((item) => item.id === id) ?? null)} onManifest={() => setManifestVisible(true)} /> : null}
          {surface === "agents" ? <DemoAgents pack={pack} runVisible={runVisible} run={() => setRunVisible(true)} /> : null}
          {surface === "replay" ? <DemoReplay pack={pack} available={runVisible} visible={replayVisible} replay={() => setReplayVisible(true)} /> : null}
          {surface === "outcome" ? <DemoOutcome pack={pack} available={runVisible} recorded={outcomeRecorded} record={() => setOutcomeRecorded(true)} /> : null}
        </section>
      </div>
      {selectedEvidence ? <div className={styles.demoModalBackdrop} role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setSelectedEvidence(null)}><section className={styles.demoModal} role="dialog" aria-modal="true" aria-labelledby="demo-evidence-title"><header><div><p className={styles.monoEyebrow}>Synthetic Evidence Ledger</p><h2 id="demo-evidence-title">{selectedEvidence.title}</h2></div><button onClick={() => setSelectedEvidence(null)} aria-label="Close evidence">×</button></header><span className={styles.demoFixtureBadge}>Synthetic fixture</span><blockquote>{selectedEvidence.excerpt}</blockquote><dl><div><dt>Source</dt><dd>{selectedEvidence.source}</dd></div><div><dt>Observed</dt><dd>{selectedEvidence.observedAt}</dd></div><div><dt>Author</dt><dd>{selectedEvidence.author}</dd></div><div><dt>Hash</dt><dd><code>{selectedEvidence.hash}</code></dd></div></dl><footer><button className={styles.primaryAction} onClick={() => setSelectedEvidence(null)}>Close evidence</button></footer></section></div> : null}
      {manifestVisible ? <div className={styles.demoModalBackdrop} role="presentation" onMouseDown={(event) => event.target === event.currentTarget && setManifestVisible(false)}><section className={styles.demoModal} role="dialog" aria-modal="true" aria-labelledby="fixture-manifest-title"><header><div><p className={styles.monoEyebrow}>Recorded fixture manifest</p><h2 id="fixture-manifest-title">{pack.name} · schema v1</h2></div><button onClick={() => setManifestVisible(false)} aria-label="Close fixture manifest">×</button></header><dl><div><dt>Classification</dt><dd>Synthetic demo only</dd></div><div><dt>Context hash</dt><dd><code>fixture:{pack.id}:v1</code></dd></div><div><dt>Evaluation result</dt><dd>24 / 24 passing</dd></div><div><dt>Live API requests</dt><dd>0</dd></div><div><dt>Entities</dt><dd>{pack.candidates.length} decision candidates</dd></div><div><dt>Evidence records</dt><dd>{pack.evidence.length}</dd></div></dl><footer><button className={styles.primaryAction} onClick={() => setManifestVisible(false)}>Close manifest</button></footer></section></div> : null}
    </main>
  );
}

function DemoOverview({ pack, onStart }: { pack: TemplatePack; onStart: () => void }) {
  return <><section className={styles.metricGrid}>{pack.metrics.map((metric) => <article key={metric.label} className={`${styles.productMetric} ${styles[`metric_${metric.tone}`]}`}><div><span>{metric.label}</span><i /></div><strong>{metric.value}</strong><small>{metric.delta}</small></article>)}</section><section className={styles.demoOverviewGrid}><article className={styles.productPanel}><header><div><p className={styles.monoEyebrow}>Recorded state propagation</p><h2>Changes waiting for review</h2></div><span>{pack.changes.length} proposed</span></header><div className={styles.activityList}>{pack.changes.map((change, index) => <div key={change.id}><span className={`${styles.activityIcon} ${styles[`severity_${change.severity}`]}`}>{index ? "↺" : "↯"}</span><div><strong>{change.subject}</strong><p>{change.predicate.replaceAll("_", " ")} → <b>{change.next}</b></p><small>{change.source}</small></div><DemoPill status="review" /></div>)}</div></article><article className={styles.demoPackCard} style={{ background: pack.accentSoft }}><span style={{ background: pack.accent }}>{pack.shortName.slice(0, 2).toUpperCase()}</span><p className={styles.monoEyebrow}>Guided workflow</p><h2>Make one safe, cited decision.</h2><p>{pack.guidedQuestion}</p><ol>{["Ask from current truth", "Review exact evidence", "Propagate one change", "Inspect the agent receipt"].map((item, index) => <li key={item}><i>0{index + 1}</i>{item}</li>)}</ol><button className={styles.primaryAction} onClick={onStart}>Start the workflow →</button></article></section></>;
}

function DemoInbox({ pack, selected, setSelected, approved, rejected, approve, reject }: { pack: TemplatePack; selected: TemplatePack["changes"][number]; setSelected: (change: TemplatePack["changes"][number]) => void; approved: string[]; rejected: string[]; approve: () => void; reject: () => void }) {
  return <section className={styles.productInbox}><div className={styles.productChangeList}><header><strong>Synthetic source events</strong><span>{pack.changes.length} total</span></header>{pack.changes.map((change) => <button key={change.id} className={selected.id === change.id ? styles.productChangeActive : styles.productChange} onClick={() => setSelected(change)}><i className={styles[`severity_${change.severity}`]} /><span><small><span className={`${styles.productSource} ${styles.productSource_synthetic}`}><i />Synthetic demo</span></small><strong>{change.subject}</strong><em>{change.predicate.replaceAll("_", " ")}</em><small>{change.source}</small></span><DemoPill status={approved.includes(change.id) ? "eligible" : rejected.includes(change.id) ? "blocked" : "review"} /></button>)}</div><article className={styles.productReview}><header><div><span className={`${styles.productSource} ${styles.productSource_synthetic}`}><i />Synthetic demo</span><h2>{selected.subject}</h2><p>{selected.source}</p></div><span><strong>{Math.round(selected.confidence * 100)}%</strong><small>confidence</small></span></header><div className={styles.claimComparison}><p className={styles.monoEyebrow}>Extracted claim · {selected.predicate}</p><div><span>−</span><p><small>Current approved value</small><strong>{selected.previous}</strong></p></div><div><span>+</span><p><small>Proposed value</small><strong>{selected.next}</strong></p></div></div><div className={styles.blastRadius}><span>↯</span><div><strong>Blast radius · {selected.impact.length} dependencies</strong><p>Approval invalidates the fixture context before the next recorded run.</p><ul>{selected.impact.map((impact) => <li key={impact}>{impact}</li>)}</ul></div></div><footer><button className={styles.secondaryAction} onClick={reject} disabled={rejected.includes(selected.id)}>{rejected.includes(selected.id) ? "Rejected ✓" : "Reject fixture"}</button><button className={styles.primaryAction} onClick={approve} disabled={approved.includes(selected.id)}>{approved.includes(selected.id) ? "Approved ✓" : "Approve and propagate →"}</button></footer></article></section>;
}

function DemoAsk({ pack, question, setQuestion, answerVisible, ask, onEvidence, onManifest }: { pack: TemplatePack; question: string; setQuestion: (value: string) => void; answerVisible: boolean; ask: () => void; onEvidence: (id: string) => void; onManifest: () => void }) {
  const [unsupported, setUnsupported] = useState(false);
  const included = [pack.guidedQuestion, ...pack.suggestedQuestions].some((item) => item.toLowerCase() === question.trim().toLowerCase());
  function runRecordedQuestion() { if (included) { setUnsupported(false); ask(); } else setUnsupported(true); }
  return <><section className={styles.productAskBox}><label htmlFor="demo-question">Ask this recorded workspace</label><textarea id="demo-question" rows={3} value={question} onChange={(event) => { setQuestion(event.target.value); setUnsupported(false); }} /><footer><span>Only the supplied guided questions are included</span><button className={styles.primaryAction} onClick={runRecordedQuestion}>Compile recorded context →</button></footer></section><div className={styles.questionChips}><span>Try:</span>{pack.suggestedQuestions.map((item) => <button key={item} onClick={() => { setQuestion(item); setUnsupported(false); }}>{item}</button>)}</div>{unsupported ? <div className={styles.demoUnsupported} role="status"><strong>Not included in this recording.</strong><span>Choose one of the supplied questions above. Commonstate will never present a canned result as a fresh answer.</span></div> : null}{answerVisible && included ? <section className={styles.productAnswer}><header><div><span>CS</span><p><small>Recorded deterministic answer</small><strong>{pack.candidates.filter((item) => item.status === "eligible").length} eligible · {pack.candidates.filter((item) => item.status !== "eligible").length} need attention</strong></p></div><div><DemoPill status="eligible" /><code>fixture:{pack.id}:v1</code></div></header><p>The following candidates satisfy this solution pack’s recorded scope, validity, evidence, and risk constraints.</p><div className={styles.candidateGrid}>{pack.candidates.map((candidate) => <article key={candidate.entityId} className={`${styles.candidateCard} ${candidate.status === "blocked" ? styles.candidateBlocked : ""}`}><header><span>{candidate.name.split(" ").map((word) => word[0]).join("").slice(0, 2)}</span><div><h3>{candidate.name}</h3><p>{candidate.subtitle}</p></div><DemoPill status={candidate.status} /></header><div className={styles.candidateScore}><i style={{ width: `${candidate.score}%` }} /><small>{candidate.score}% policy match</small></div><dl>{candidate.facts.map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl><p className={styles.candidateReason}>{candidate.status === "eligible" ? "✓" : candidate.status === "blocked" ? "⊘" : "!"} {candidate.reason}</p><footer>{candidate.evidenceIds.map((id, index) => <button key={id} onClick={() => onEvidence(id)}>Evidence {index + 1} ↗</button>)}</footer></article>)}</div><footer><span><strong>Honest recorded mode</strong><small>Synthetic fixture · fixed context hash · no live company API requests</small></span><button onClick={onManifest}>Inspect fixture manifest →</button></footer></section> : !unsupported ? <section className={styles.productEmpty}><div className={styles.emptyStateGlyph}><span>CS</span><i /><i /></div><h2>Ask the pack&apos;s core question.</h2><p>This public demo is deterministic. It never presents a canned fixture as fresh company data.</p></section> : null}</>;
}

function DemoAgents({ pack, runVisible, run }: { pack: TemplatePack; runVisible: boolean; run: () => void }) {
  return <><div className={styles.agentStatusStrip}><span><i />{pack.agents.length} configured fixture agents</span><span>Dry-run only</span><span>Critical actions blocked</span><span>Synthetic evidence</span></div><section className={styles.productAgentLayout}><div className={styles.productAgentList}>{pack.agents.map((agent, index) => <article key={agent.id} className={index === 0 ? styles.productAgentActive : styles.productAgentCard}><header><span>{agent.initials}</span><div><h3>{agent.name}</h3><p>{agent.purpose}</p></div><DemoPill status={index === 0 ? "eligible" : "review"} /></header><dl><div><dt>Scope</dt><dd>{agent.scope}</dd></div><div><dt>Write budget</dt><dd>{agent.writeBudget}</dd></div><div><dt>Risk ceiling</dt><dd>{agent.riskCeiling}</dd></div></dl></article>)}</div><article className={styles.agentRunPanel}><header><div><p className={styles.monoEyebrow}>Recorded run</p><h2>{pack.guidedQuestion}</h2></div><DemoPill status={runVisible ? "eligible" : "review"} /></header>{!runVisible ? <div className={styles.agentReady}><div><span>CS</span><i /><i /><i /></div><h3>Run the template agent against fixture state.</h3><p>Inspect the context, policy, and evidence boundary without triggering any real external action.</p><button className={styles.primaryAction} onClick={run}>Run recorded agent →</button></div> : <div className={styles.receiptView}><div className={styles.receiptHash}><span>Immutable fixture receipt</span><code>sha256:{pack.id}:context-v1</code></div><div className={styles.receiptTimeline}>{["Synthetic identity resolved", "Minimal context compiled", "Risk policy applied", "Dry-run receipt recorded"].map((item, index) => <div key={item}><span>{index + 1}</span><p><strong>{item}</strong><small>Deterministic pass</small></p><DemoPill status="eligible" /></div>)}</div></div>}</article></section></>;
}

function DemoReplay({ pack, available, visible, replay }: { pack: TemplatePack; available: boolean; visible: boolean; replay: () => void }) {
  if (!available) return <section className={styles.productEmpty}><div className={styles.emptyStateGlyph}><span>↺</span><i /><i /></div><h2>Run the recorded agent first.</h2><p>Replay requires an immutable fixture receipt. Open Agent Console, run the deterministic agent, then return here.</p></section>;
  return <section className={styles.replayShell}><header><div><span>Baseline fixture run</span><strong>run_{pack.id}_baseline</strong><small>Context hash · v1</small></div><i>→</i><div><span>Approved fixture state</span><strong>{visible ? "Replay complete" : "Ready to compare"}</strong><small>{pack.changes.length} proposed source events</small></div></header><div className={styles.replayCompare}><article><p className={styles.monoEyebrow}>What the agent knew then</p><h2>Original context</h2><dl><div><dt>Solution pack</dt><dd>{pack.name}</dd></div><div><dt>Context hash</dt><dd><code>fixture:{pack.id}:baseline</code></dd></div><div><dt>Decision candidates</dt><dd>{pack.candidates.length}</dd></div></dl><aside><span>✓</span><p><strong>Historical receipt preserved</strong><small>Original evidence and configuration remain immutable.</small></p></aside></article><article className={visible ? styles.replayChanged : ""}><p className={styles.monoEyebrow}>What the agent would know now</p><h2>{visible ? "Current-state comparison" : "Awaiting replay"}</h2>{visible ? <><dl><div><dt>Changed claims</dt><dd>{pack.changes.length}</dd></div><div><dt>Blocked candidates</dt><dd>{pack.candidates.filter((item) => item.status === "blocked").length}</dd></div><div><dt>Policy result</dt><dd>Fail-closed applied</dd></div></dl><aside><span>↯</span><p><strong>Blast radius recalculated</strong><small>The new context changes unsafe actions into explicit holds.</small></p></aside></> : <div className={styles.replayPlaceholder}><span>↺</span><p>Compare the original receipt with the newly approved fixture state.</p><button className={styles.primaryAction} onClick={replay}>Run temporal replay →</button></div>}</article></div><footer><span>Same hash → reproducible</span><span>Changed state → explicit diff</span><span>0 live API requests</span></footer></section>;
}

function DemoOutcome({ pack, available, recorded, record }: { pack: TemplatePack; available: boolean; recorded: boolean; record: () => void }) {
  if (!available) return <section className={styles.productEmpty}><div className={styles.emptyStateGlyph}><span>◎</span><i /><i /></div><h2>No recorded run to measure.</h2><p>Run the fixture agent first. Outcomes always stay bound to the decision receipt that produced them.</p></section>;
  return <section className={styles.demoOutcome}><article><p className={styles.monoEyebrow}>Outcome Memory · synthetic</p><h2>{recorded ? "Learning proposed for review." : "Close the decision loop."}</h2><p>{recorded ? "The fixture outcome is now a proposed memory—not self-approved source truth." : "Record deterministic sample metrics against the agent receipt and send the resulting learning to Change Inbox."}</p><dl>{pack.outcomeMetrics.map((metric, index) => <div key={metric.key}><dt>{metric.label}</dt><dd>{index === 0 ? "18.4" : index === 1 ? "3.2" : "1"} <small>{metric.unit}</small></dd></div>)}</dl><button className={styles.primaryAction} onClick={record} disabled={recorded}>{recorded ? "Outcome recorded ✓" : "Record synthetic outcome →"}</button></article><aside><div><span>01</span><p><strong>Decision receipt</strong><small>run_{pack.id}_baseline</small></p><DemoPill status="eligible" /></div><i>↓</i><div><span>02</span><p><strong>Measured result</strong><small>{pack.outcomeMetrics.length} synthetic metrics</small></p><DemoPill status={recorded ? "eligible" : "review"} /></div><i>↓</i><div><span>03</span><p><strong>Proposed learning</strong><small>Human review required</small></p><DemoPill status={recorded ? "review" : "blocked"} /></div><footer><strong>Agents cannot validate their own summaries.</strong><span>Outcome learning enters the same evidence-backed Truth Workflow as every other proposed claim.</span></footer></aside></section>;
}
